FROM swr.cn-central-221.ovaijisuan.com/mindxsdk/mindspore_1.8_text2image:v0

# USER root

COPY pretraind_models/cog-pretrain.model /home/server/pretraind_models/cog-pretrain.model
COPY pretraind_models/glide_gen.ckpt /home/server/pretraind_models/glide_gen.ckpt
COPY pretraind_models/glide_super_res.ckpt /home/server/pretraind_models/glide_super_res.ckpt
COPY pretraind_models/srgan.ckpt /home/server/pretraind_models/srgan.ckpt

COPY requirements.txt /tmp/requirements.txt

RUN pip install pip -U -i https://pypi.tuna.tsinghua.edu.cn/simple/ \
    && pip install -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

COPY model /home/server/model
COPY model_configs /home/server/model_configs
COPY scripts /home/server/scripts
COPY src /home/server/src


WORKDIR /home/server

CMD ["bash", "./scripts/run_server_docker.sh"]
